#cloud-config
package_update: true
package_upgrade: false

packages:
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

runcmd:
  - [ bash, -lc, "install -m 0755 -d /etc/apt/keyrings" ]
  - [ bash, -lc, "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg" ]
  - [ bash, -lc, "chmod a+r /etc/apt/keyrings/docker.gpg" ]
  - [ bash, -lc, "echo \"deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo $VERSION_CODENAME) stable\" > /etc/apt/sources.list.d/docker.list" ]
  - [ bash, -lc, "apt-get update" ]
  - [ bash, -lc, "apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin" ]
  - [ bash, -lc, "usermod -aG docker ubuntu" ]
  - [ bash, -lc, "systemctl enable --now docker" ]
  - [ bash, -lc, "docker --version" ]
  - [ bash, -lc, "docker compose version" ]
